version: '3'
services:
  # redis-server:
  #   image: 'redis'
  #   networks:
  #     - mynetwork
  node-app:
    restart: always
    build: .
    ports: 
      - "4001:8081"
    networks:
      - mynetwork
networks:
  mynetwork: